### ISSUE TITLE
Raven Issue

### ISSUE THREAD

**Issue by ShamilSd** [PythonBalkan/pyconbalkan#125]
Raven not configured?
![2018-10-11 2](https://user-images.githubusercontent.com/36222156/46814085-9c3f1080-cd95-11e8-8979-08ac9949120d.png)

**Comment by ulgens** [comment]
It's normal for development environment.

**Comment by ShamilSd** [comment]
The site is not running

**Comment by virogenesis** [comment]
Closing this.
